name: master branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4 # ssh 접속하는 오픈소스

      - name: Execute Deployment Commands on EC2
        env:
          EC2_HOST: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          EC2_USER: ${{ secrets.REMOTE_USER }} # 우분투 아이디
        run: |
          echo "${{secrets.REMOTE_PRIVATE_KEY}}" > ec2_key.pem
          chmod 600 ec2_key.pem
          
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
             cd /home/ubuntu/final
             git fetch
             git pull origin master
             pm2 kill
             npm i --legacy-peer-deps  
             npm run build
             pm2 start dist/main.js
          EOF
          
          rm -f ec2_key.pem
